### ISSUE TITLE
如何在用这个模版，修改页面上的内容呢

### ISSUE THREAD

**Issue by Sherlockouo** [loo-y/nextextension-starter#1]
能不能用ui框架来做插入内容呢

**Comment by loo-y** [comment]
你是说在页面上插入自己的内容吗？可以参照这个实际的插件：
https://github.com/loo-y/weibo-extend/blob/main/app/scripts/content/injects.ts

在content 里面插入 renderVirtualPage
VirtualPage是一个 react 的 Page，可以使用 tailwindcss或者其他 ui 组件，最后都会打包到插件里面。

**Comment by Sherlockouo** [comment]
> 你是说在页面上插入自己的内容吗？可以参照这个实际的插件： https://github.com/loo-y/weibo-extend/blob/main/app/scripts/content/injects.ts
> 
> 在content 里面插入 renderVirtualPage VirtualPage是一个 react 的 Page，可以使用 tailwindcss或者其他 ui 组件，最后都会打包到插件里面。

ok, 我去试试，感谢
